### ISSUE TITLE
Full-Framework-Support (.NEt 4.x)

### ISSUE THREAD

**Issue by rs042009** [awaescher/OllamaSharp#27]
Hi Team,

We are working on .Net Framework 4.7.2.  Any plan for supporting this?

Thanks,
Rajesh K.

**Comment by awaescher** [comment]
Hi Rajesh, I am not planning to add full framework support.
The main reason is that I am using `System.Text.Json` which is not available in .NET 4.x.

You're welcome to fork this repository.

**Comment by awaescher** [comment]
OllamaSharp targets .NET Standard now, which was implemented with #30

**Comment by awaescher** [comment]
No. If a library targets .NET Standard, it's only using a subset of functions that are available in .NET and .NET Framework. 
That means, OllamaSharp can indeed be used with .NET Framework.

The question is: Why won't you just take 3min and try?

**Comment by rgelbjw** [comment]
@awaescher I couldn't.  That's why I asked - I thought I was missing something.  For instance, I created up a new .NET 4.8 console project.  Attempting to add OllamaSharp nuget package results in:

```
Attempting to gather dependency information for package 'OllamaSharp.5.1.4' with respect to project 'OllamaClient', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 875 ms
Attempting to resolve dependencies for package 'OllamaSharp.5.1.4' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'Microsoft.Extensions.AI.Abstractions'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages', 'DevExpress', 'DevExpress 23.2 Local', 'local'.
```

**Comment by awaescher** [comment]
Alright, I understand. Could be a NuGet issue. Install `Microsoft.Extensions.Ai.Abstractions` in the given version manually. This is going to work.

**Comment by rgelbjw** [comment]
@awaescher I got it to work, but there are lots of hoops to jump through.  Here are the workarounds, if anyone runs into these issues. 

Problem 1.  The nuget issues.  It's possible that OllamaSharp nuget installer doesn't recognize `Microsoft.Extensions.Ai.Abstractions` because it's prerelease.  So to get around it, I installed `Microsoft.Extensions.Ai.Abstractions` first (with the prerelease checkbox on), then OllamaSharp.  The basic code listing the models compiled.

Problem 2.  The patterns described on the home page like:

```csharp
await foreach (var stream in ollama.GenerateAsync("How are you today?"))
    Console.Write(stream.Response);
```

do not work because .NET 48 uses c# 7.3 doesn't support 'using declarations'.  These patterns are used all over the library so you have to work around them.  And you can't iterate IAsyncEnumerable automatically - the language version doesn't support it.  You have to do manually.

So the code above becomes:

```csharp
IAsyncEnumerable<GenerateResponseStream> responses = ollamaClient.GenerateAsync("why is the sky blue");
await IterateAsyncEnumerable(responses);

static async Task IterateAsyncEnumerable<T>(IAsyncEnumerable<T> asyncEnumerable, CancellationToken cancellationToken = default) {
    var enumerator = asyncEnumerable.GetAsyncEnumerator(cancellationToken);
    try {
        while (await enumerator.MoveNextAsync()) {
            PrintResponse(enumerator.Current);
        }
    } finally {
        await enumerator.DisposeAsync(); // Manual disposal since 'await using' is not available
    }
}

static void PrintResponse(object obj ) {
    GenerateResponseStream grs = obj as GenerateResponseStream;
    Console.Write(grs.Response);
}
```

This was my solution - seems "extra".  There is probably a simpler way, but that's how I was able to make it work.

**Comment by awaescher** [comment]
Thanks for this. Kind of expected. You are using 6+ years old framework that has not evolved and does not get language feature updates.

However I should mention, that I implemented a method `StreamToEnd()` which is part of OllamaSharp. `StreamToEnd()` streams the async enumerable and waits till it finished. If you want to update the UI like adding the streamed tokens to the console, you can pass a delegate to that method that gets executed anytime a token gets streamed. Should be very convenient.

**Comment by rgelbjw** [comment]
Oh, that is actually perfect.  The code now becomes:

```csharp
await ollamaClient.GenerateAsync("why is the sky blue").StreamToEndAsync(PrintResponse);

private static void PrintResponse(GenerateResponseStream stream) {
    Console.Write(stream.Response);
}
```

Much simpler.  Thank you very much!

**Comment by awaescher** [comment]
100% correct 👍🏻
